### ISSUE TITLE
Errors opening CharAnim.uproject (Exercise 2.05)

### ISSUE THREAD

**Issue by bastianovic-dev** [PacktPublishing/Elevating-Game-Experiences-with-Unreal-Engine-5-Second-Edition#2]
Unreal Editor gives the following errors when opening CharAnim.uproject (Exercise 2.05):

The summary for the package '/Game/ThirdPersonBP/Blueprints/ThirdPersonCharacter' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/ThirdPersonBP/Maps/ThirdPersonExampleMap_BuiltData' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/Geometry/Meshes/1M_Cube' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/Geometry/Meshes/1M_Cube_Chamfer' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/Geometry/Meshes/TemplateFloor' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/ThirdPerson/Meshes/Bump_StaticMesh' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/ThirdPerson/Meshes/LeftArm_StaticMesh' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/ThirdPerson/Meshes/Linear_Stair_StaticMesh' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/ThirdPerson/Meshes/Ramp_StaticMesh' is invalid. Check that the file is of the expected type and not corrupted.
The summary for the package '/Game/ThirdPerson/Meshes/RightArm_StaticMesh' is invalid. Check that the file is of the expected type and not corrupted.
CreateExport: Failed to load Outer for resource 'Arrow': ThirdPersonCharacter_C /Game/ThirdPersonBP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonCharacter_167
CreateExport: Failed to load Outer for resource 'FollowCamera': ThirdPersonCharacter_C /Game/ThirdPersonBP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonCharacter_167
CreateExport: Failed to load Outer for resource 'CollisionCylinder': ThirdPersonCharacter_C /Game/ThirdPersonBP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonCharacter_167
CreateExport: Failed to load Outer for resource 'CharMoveComp': ThirdPersonCharacter_C /Game/ThirdPersonBP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonCharacter_167
CreateExport: Failed to load Outer for resource 'CharacterMesh0': ThirdPersonCharacter_C /Game/ThirdPersonBP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonCharacter_167
CreateExport: Failed to load Outer for resource 'CameraBoom': ThirdPersonCharacter_C /Game/ThirdPersonBP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonCharacter_167

Version: 5.0.3-20979098+++UE5+Release-5.0

**Comment by Ilan1903** [comment]
Had the same issue. Try getting it through git clone, instead of downloading zip files directly. It solved the problem for me.

**Comment by bastianovic-dev** [comment]
> Had the same issue. Try getting it through git clone, instead of downloading zip files directly. It solved the problem for me.

Works like a charm! Thank you very much!
