### ISSUE TITLE
[UE 5.3] Activity 7.01 : SetTarget results in an access violation writing location

### ISSUE THREAD

**Issue by Guendeli** [PacktPublishing/Elevating-Game-Experiences-with-Unreal-Engine-5-Second-Edition#5]
the method in LookAtActorComponent.h
```
FORCEINLINE void SetTarget(AActor* NewTarget) { TargetActor = NewTarget; }
```

Results in an access violation and crashes the editor, i've tried:
- adding a UProperty() above it
- Initializing the pointer in the constructor
- using the recommended TObjectPtr<T> instead of Raw pointer

Results is the same, crashes the editor

**Comment by goncasmage1** [comment]
Hi,

That's very weird. Are you sure you did all the steps correctly? The only way for that to cause an access violation, I think, is if the LootAtActorComponent reference you're calling the function from is null, but it should never be because it's initialized using CreateDefaultSubobject 🤔

**Comment by Guendeli** [comment]
Closed, it was related to how the new live coding works. A clean rebuild fixed it.
